### ISSUE TITLE
Nested gem in a git repo with rust compilation --  produces git error and corrupts install

### ISSUE THREAD

**Issue by tsmartt** [ruby/rubygems#4838]
### Describe the problem as clearly as you can

Compilation on linux of a rust-compiled gem referenced by git, where the gem is in a subdirectory causes future gem references to fail. 

See https://github.com/brave-intl/publishers/runs/3302463319

### Post steps to reproduce the problem

We run our CI deployment on docker, with the run that is failing being here:

https://github.com/brave-intl/publishers/runs/3302463319

* Ruby 2.7 on ruby slim docker
* bundler and ruby use standard commands

If I take the gem which references 
```
gem "wasm-thumbnail-rb", git: 'https://github.com/brave-intl/wasm-thumbnail.git', tag: '0.0.3'
```
 out, the `bundle exec rails assets:precompile` command succeeds, which means it can find the installed gems in a later command. If I put it in, then bundler can't find rails later on.

I managed to work around it by installing the [wasmer gem first in cache mode](https://github.com/brave-intl/publishers/pull/3358/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R40).

It seems there is a problem installing from git:

```
ar/www/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/wasmer-1.0.0
fatal: not a git repository (or any of the parent directories): .git
bundle config set --local path "vendor/bundle"
bundle install
The deployment setting requires a Gemfile.lock. Please make sure you have
checked your Gemfile.lock into version control before deploying.
rake aborted!
Command failed with status (16): [bundle install...]
/var/www/vendor/bundle/ruby/2.7.0/gems/wasmer-1.0.0/Rakefile:12:in `block in
<top (required)>'
/var/www/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<main>'
Tasks: TOP => default => test => bundle_install
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in
/var/www/vendor/bundle/ruby/2.7.0/gems/wasmer-1.0.0 for inspection.
Results logged to
/var/www/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/wasmer-1.0.0/gem_make.out

  /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
  /usr/local/lib/ruby/2.7.0/rubygems/ext/rake_builder.rb:30:in `build'
/usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in
build_extension'
  /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `synchronize'
  /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `build_extension'
/usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in
build_extensions'
```

**Comment by deivid-rodriguez** [comment]
I had a look at `wasmer-ruby`'s `Rakefile` and it tries to run `bundle install` and other `bundle` commands inside a `Rakefile` extension: https://github.com/wasmerio/wasmer-ruby/blob/c1b554b5b3d14f17405940dc6c0951b898113ef1/Rakefile#L1-L22.

I've never seen something like that, and I don't really expect it to be supported. From a quick look, I think they want to run their own tests before the gem is installed, and they need to `bundle install` inside the unpackaged library as a prerequisite for that. I would recommend that they remove all that and they stick to building the rust artifact.

As per the actual culprit, I think it's because when `git` gems are present, `bundler` still needs to do one global `chdir` for gemspec serialization, so probably due to a race condition, `bundle install` in the extension is finding itself in the wrong folder.

**Comment by deivid-rodriguez** [comment]
I'm going to give removing the mentioned `Dir.chdir` a try. It's the only global folder switching we have left, so it would make `bundler` fully thread safe in this regard, so it's worth a try. If I find a way to remove it, that might fix this issue, but I'm not sure when I'll get to it and I feel it's till going to be problematic to keep running `wasmer-ruby`'s tests at `bundle install` time. Although it's an interesting idea, I would rather make sure tests are green before release and remove that from the `Rakefile` extension.

**Comment by deivid-rodriguez** [comment]
I'm now reading the discussion in your PR and I understand that `bundle install` is actually needed for the extension to work properly? I'm not fully sure why since the gem seems to have no ruby dependencies, but in any case, I think an alternative fix for the issue would be to change the bundle commands like this:

```diff
- sh 'bundle config set --local path "vendor/bundle"'
- sh 'bundle install'
- sh 'cd vendor/bundle && ln -f -s ruby/*/gems/rutie-*/ rutie'
+ sh "cd #{__dir__} && bundle config set --local path vendor/bundle"
+ sh "cd #{__dir__} && bundle install"
+ sh "cd #{__dir__}/vendor/bundle && ln -f -s ruby/*/gems/rutie-*/ rutie"
```

so that they don't depend on the global CWD.

**Comment by tsmartt** [comment]
That's a nice thought, I put up a PR to wasmer to remove the bundle install from gem installation via the Rakefile. It fixed the issue on our end, which was my concern. Thanks for all of the help!

**Comment by hsbt** [comment]
Fixed in e600431656. Building an extension no longer changes the CWD of the whole Ruby process, so the corruption reported here can no longer happen.
