### ISSUE TITLE
`bundler gem` on Windows fails when initializing a Git repository for a path that contains spaces

### ISSUE THREAD

**Issue by TheNathannator** [ruby/rubygems#8351]
### Describe the problem as clearly as you can

On Windows, when inside a directory path with spaces such as `E:\Programming\Source\New folder`, running `bundler gem` to create a new gem fails after `git init` due to improper shell escaping on the path. `git init` never actually runs and simply displays its help info, so bundler subsequently fails when trying to read `.git/HEAD`.

This appears to be due to the usage of `shellwords`, which performs Bash-style escaping and turns the path into `E:/Programming/Source/New\ folder/gem_test`. This doesn't work for escaping paths in Powershell or CMD, instead the path should be quoted (`"E:/Programming/Source/New folder/gem_test"`).

This is a fairly edge-case issue given that it's uncommon to use file or folder names that contain spaces in general programming, but I figure it's still worth reporting since the command output does not make the problem apparent.

### Did you try upgrading rubygems & bundler?

I have verified I am using the latest version of both (rubygems 3.6.1, bundler 2.6.1).

### Post steps to reproduce the problem

1. Create a new folder which contains spaces in the name (such as the default `New folder`).
2. Open a command prompt to the folder and run `bundler gem gem_test`.
3. Observe that `git init` emitted usage instructions instead of initializing a repository, and that the subsequent attempt to open `.git/HEAD` fails.

### Which command did you run?

`PS E:\Programming\Source\New folder> bundler gem gem_test`

### What were you expecting to happen?

`bundler gem` should have run without errors.

### What actually happened?

```
PS E:\Programming\Source\New folder> bundler gem gem_test
Creating gem 'gem_test'...
MIT License enabled in config
Changelog enabled in config
RuboCop enabled in config
Initializing git repo in E:/Programming/Source/New folder/gem_test
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>]
         [--separate-git-dir <git-dir>] [--object-format=<format>]
         [--ref-format=<format>]
         [-b <branch-name> | --initial-branch=<branch-name>]
         [--shared[=<permissions>]] [<directory>]
```

```
Errno::ENOENT: No such file or directory @ rb_sysopen - E:/Programming/Source/New folder/gem_test/.git/HEAD
  d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/cli/gem.rb:226:in `read'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/cli/gem.rb:226:in `run'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:553:in `gem'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:538:in `dispatch'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:29:in `start'
          d:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.1/exe/bundle:28:in `block in <top (required)>'
          d:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          d:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.1/exe/bundle:20:in `<top (required)>'
          d:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.1/exe/bundler:4:in `load'
          d:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.1/exe/bundler:4:in `<top (required)>'
          D:/Ruby33-x64/bin/bundler:36:in `load'
          D:/Ruby33-x64/bin/bundler:36:in `<main>'

```

## Environment

```
Bundler       2.6.1
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.3.6p108 (2024-11-05 revision 75015d4c1f6965b5e85e96fb309f1f2129f933c0) [x64-mingw-ucrt]
  Full Path   d:/Ruby33-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.6.1
  Gem Home    d:/Ruby33-x64/lib/ruby/gems/3.3.0
  Gem Path    C:/Users/natha/.local/share/gem/ruby/3.3.0;d:/Ruby33-x64/lib/ruby/gems/3.3.0
  User Home   C:/Users/natha
  User Path   C:/Users/natha/.local/share/gem/ruby/3.3.0
  Bin Dir     d:/Ruby33-x64/bin
Tools
  Git         2.45.2.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Gem.ruby      d:/Ruby33-x64/bin/ruby.exe
bundle #!     /bin/sh

```

## Bundler Build Metadata

```
Built At          2024-12-17
Git SHA           00a344e02c8
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (C:/Users/natha/.bundle/config): true
gem.ci
  Set for the current user (C:/Users/natha/.bundle/config): false
gem.coc
  Set for the current user (C:/Users/natha/.bundle/config): false
gem.linter
  Set for the current user (C:/Users/natha/.bundle/config): "rubocop"
gem.mit
  Set for the current user (C:/Users/natha/.bundle/config): true
gem.test
  Set for the current user (C:/Users/natha/.bundle/config): "minitest"
```

**Comment by deivid-rodriguez** [comment]
Thank you for the report, we should fix this! Would you be open to try fixing this yourself, since you are on Windows and can reproduce the error easily? I'm happy to help out!

**Comment by TheNathannator** [comment]
Apologies for not responding sooner!

I certainly could try to fix this myself, though I'm not currently that well versed in Ruby things or the differences between command parsing across the different platforms to know what the ideal/recommended way to fix this would be, so I'm not personally confident in doing so lol

The easiest solution would be to handle things in a more platform-specific way here, given the notable behavior differences (particularly string handling and escape characters), and just surround the path with strings on Windows specifically. Whether that would be the ideal solution is another question altogether, e.g. if there's a library or gem that already handles these details properly, so that they don't need to be re-implemented manually here. Any thoughts and guidance is appreciated!

**Comment by deivid-rodriguez** [comment]
Indeed it seems I tried to fix precisely this case in https://github.com/rubygems/rubygems/blob/efdff2bb70ff4716d3321b1866fb4c6195000373/bundler/lib/bundler/cli/gem.rb#L226, but I did not know this would not work in Windows shells. I suggest to try your suggestion of quoting instead of escaping, maybe that will do the trick.

**Comment by hsbt** [comment]
Fixed in c98aa10c743. `bundle gem` runs `git init` through an argument array now, so the target path never passes through shell escaping. If it still reproduces on the current stable release in your environment, please let me know.

**Comment by hsbt** [comment]
Sorry, I verified this against master. It is not fixed in 4.0.x. It ships in RubyGems 4.1.0, which is coming soon.
